# Generated by Django 3.2.16 on 2023-09-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text2',
        ),
    ]
